# Generated by Django 3.2.3 on 2021-06-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_accomplishments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='BlogUser',
        ),
        migrations.AlterModelOptions(
            name='bloguser',
            options={'verbose_name': 'Blog User', 'verbose_name_plural': 'Blog Users'},
        ),
    ]
